In [15]:
import numpy as np
import pandas as pd

In [16]:
def _euclidean(x,y):
    total=np.sum((x-y)**2) ** 0.5
    return total

def _minskowski(x,y):
    total=np.sum(abs(x-y))
    return total

In [23]:
raw_data=pd.read_csv('DatasetDBSCAN.csv')
raw_data

   No  Temperatur (T)  Kelembapan (K)  Initial Cluster
0   1              85              85                0
1   2              80              90                0
2   3              65              70                0
3   4              72              95                0
4   5              83              78                0
5   6              60              75                0
6   7              78              85                0
7   8              64              65                0
8   9              69              70                0
9  10              75              88                0

In [24]:
array_data=raw_data.drop('No',axis=1)
array_data=array_data.values

In [25]:
def getNeighbors(X,P,eps):
    
    #X : Semua point yg ada di dataset
    #P : Point yg ditunjuk sebagai patokan (pusat untuk menghitung distance ke point lain)
    #eps : radius 
    seeds=[]
    for i in range(0,len(X)):
#         for j in range(len(X[i])):
        distance = _minskowski(P,X[i])
        if distance<eps and distance!=0:
            seeds.append(i)
    return np.array(seeds)

#_region_query(np.array([[65, 70], [80, 90]]), np.array([65, 70]), 0.3)

def expandCluster(X,NeighborPts,C,eps,minPts):
    
    #X: Semua point yg ada pada dataset
    #NeighborsPts : semua index yg merupakan ketetanggaan hasil dari perhitungan minskowski
    #C : Label untuk cluster baru 
    i=0
    while i <len(NeighborPts):
        next_point=NeighborPts[i]
        if X[next_point,-1]==-1:
            X[next_point,-1]=C
            
        elif X[next_point,-1]==0:
            X[next_point,-1]=C
            
            next_point_neighborPts=getNeighbors(X[:,:-1],X[next_point,:-1],eps)
            
            if len(next_point_neighborPts)>=minPts:
                print("Next Neighbor", next_point_neighborPts)
                print(X)
                NeighborPts= np.unique(np.concatenate((NeighborPts,next_point_neighborPts)))
                print(NeighborPts)
        i+=1

In [26]:
def dbscan(X,eps,minPts):
#     labels=[0]*len(X)
    C=0
    
    listClust = X[:,-1] # Get reference to all cluster point
    while np.count_nonzero(listClust) < len(listClust): # Selama count non zero < panjang list cluster, berarti masih ada nilai 0
        randInt = np.random.randint(0, len(listClust)) # generate random index
        print("start index", randInt)
        if not (X[randInt,-1]==0):
            continue
        
        NeighborPts=getNeighbors(X[:,:-1],X[randInt,:-1],eps)
        print("First Neighbor", NeighborPts)
        
        if len(NeighborPts)<minPts:
            X[randInt,-1]=-1
        else :
            C+=1
            X[randInt,-1] = C
            print(X)
            expandCluster(X,NeighborPts,C,eps,minPts)
            
        print('Cluster Result\n', X, '\n')
    return X

In [27]:
array_data = dbscan(array_data,15,4)
# print(array_data)

start index 5
First Neighbor [2 7 8]
Cluster Result
 [[85 85  0]
 [80 90  0]
 [65 70  0]
 [72 95  0]
 [83 78  0]
 [60 75 -1]
 [78 85  0]
 [64 65  0]
 [69 70  0]
 [75 88  0]]

start index 0
First Neighbor [1 4 6 9]
[[85 85  1]
 [80 90  0]
 [65 70  0]
 [72 95  0]
 [83 78  0]
 [60 75 -1]
 [78 85  0]
 [64 65  0]
 [69 70  0]
 [75 88  0]]
Next Neighbor [0 3 6 9]
[[85 85  1]
 [80 90  1]
 [65 70  0]
 [72 95  0]
 [83 78  0]
 [60 75 -1]
 [78 85  0]
 [64 65  0]
 [69 70  0]
 [75 88  0]]
[0 1 3 4 6 9]
Next Neighbor [0 1 4 9]
[[85 85  1]
 [80 90  1]
 [65 70  0]
 [72 95  1]
 [83 78  1]
 [60 75 -1]
 [78 85  1]
 [64 65  0]
 [69 70  0]
 [75 88  0]]
[0 1 3 4 6 9]
Next Neighbor [0 1 3 6]
[[85 85  1]
 [80 90  1]
 [65 70  0]
 [72 95  1]
 [83 78  1]
 [60 75 -1]
 [78 85  1]
 [64 65  0]
 [69 70  0]
 [75 88  1]]
[0 1 3 4 6 9]
Cluster Result
 [[85 85  1]
 [80 90  1]
 [65 70  0]
 [72 95  1]
 [83 78  1]
 [60 75 -1]
 [78 85  1]
 [64 65  0]
 [69 70  0]
 [75 88  1]]

start index 0
start index 3
start index 7
First Neighbor [2 5 8]
Cluster Result
 [[85 85  1]
 [80 90  1]
 [65 70  0]
 [72 95  1]
 [83 78  1]
 [60 75 -1]
 [78 85  1]
 [64 65 -1]
 [69 70  0]
 [75 88  1]]

start index 9
start index 5
start index 1
start index 7
start index 4
start index 5
start index 2
First Neighbor [5 7 8]
Cluster Result
 [[85 85  1]
 [80 90  1]
 [65 70 -1]
 [72 95  1]
 [83 78  1]
 [60 75 -1]
 [78 85  1]
 [64 65 -1]
 [69 70  0]
 [75 88  1]]

start index 1
start index 5
start index 2
start index 8
First Neighbor [2 5 7]
Cluster Result
 [[85 85  1]
 [80 90  1]
 [65 70 -1]
 [72 95  1]
 [83 78  1]
 [60 75 -1]
 [78 85  1]
 [64 65 -1]
 [69 70 -1]
 [75 88  1]]

In [28]:
array_data

array([[85, 85,  1],
       [80, 90,  1],
       [65, 70, -1],
       [72, 95,  1],
       [83, 78,  1],
       [60, 75, -1],
       [78, 85,  1],
       [64, 65, -1],
       [69, 70, -1],
       [75, 88,  1]])

2